# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-12 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotogether', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='imageURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='number_of_guests',
            field=models.IntegerField(default=1),
        ),
    ]
