# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-17 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gotogether', '0002_auto_20161212_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotogether.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotogether.User')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotogether.Business')),
            ],
        ),
    ]
