# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-18 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotogether', '0003_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='fishing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='rockclimbing',
            field=models.BooleanField(default=False),
        ),
    ]
