# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-18 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotogether', '0005_auto_20161218_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='distance',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='options',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='options',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
